services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OPENAI_API_KEY=${OPENAI_API_KEY:?set OPENAI_API_KEY in .env}'
      - 'WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:?set WEBUI_SECRET_KEY in .env}'
      - 'WEBUI_NAME=Idilio Chat'
      - 'ENABLE_GOOGLE_DRIVE_INTEGRATION=${ENABLE_GOOGLE_DRIVE_INTEGRATION-False}'
      - 'GOOGLE_DRIVE_CLIENT_ID=${GOOGLE_DRIVE_CLIENT_ID-}'
      - 'GOOGLE_DRIVE_API_KEY=${GOOGLE_DRIVE_API_KEY-}'
      - 'REDSHIFT_URL=${REDSHIFT_URL-}'
      - 'GITHUB_TOKEN=${GITHUB_TOKEN-}'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}
